production:
  adapter: mysql2
  encoding: utf8
  host: <%= ENV.fetch('MYSQL_HOST') %>
  database: <%= ENV['MYSQL_DATABASE'] %>
  username: <%= ENV['MYSQL_USERNAME'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  
development:
  adapter: mysql2
  encoding: utf8
  host: <%= ENV.fetch('MYSQL_HOST') %>
  database: <%= ENV['MYSQL_DATABASE'] %>
  username: <%= ENV['MYSQL_USERNAME'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>

test: &test
  adapter: mysql2
  encoding: utf8
  host: <%= ENV.fetch('MYSQL_HOST') %>
  database: <%= ENV['MYSQL_DATABASE'] %>
  username: <%= ENV['MYSQL_USERNAME'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
